# Generated by Django 4.2 on 2025-03-15 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0003_test1_test2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test2",
            name="test1",
        ),
        migrations.DeleteModel(
            name="Test1",
        ),
        migrations.DeleteModel(
            name="Test2",
        ),
    ]
